easy_admin:
    entities:
        # List the entity class name you want to manage
        Utilisateur:
            class: App\Entity\EterUser
            form:
                fields:
                    - {property: 'user_login', label: 'Pseudo'}
                    - {property: 'user_mail', label: 'Adresse mail'}
                    - {property: 'user_address', label: 'Adresse'}
                    - {property: 'user_zip', label: 'Code postal'}
                    - {property: 'user_city', label: 'Ville'}
                    - {property: 'user_discord', label: 'Discord'}
                    - {property: 'statut', label: 'Etat'}
                    - {property: 'label', label: 'Etiquette'}
                    - {property: 'user_role', label: 'Rôle'}
                    - {property: 'user_clan', label: 'Clan'}
                    - {property: 'user_game', label: 'Jeux joués'}
                    - {property: 'user_pic', type: 'file', label: 'photo de profil'}
            list:
                fields:
                    - {property: 'user_login', label: 'Pseudo'}
                    - {property: 'user_avatar',type: 'image', label: 'photo de profil', base_path: '/eter/public/img/upload/profil_pic'}
                    - {property: 'role', label: 'Rôle'}
                    - {property: 'user_clan', label: 'Clan'}
                    - {property: 'user_mail', label: 'Adresse mail'}
                    - {property: 'statut', label: 'Etat'}
                actions:
                    - {name: 'edit', icon: 'pencil', label: false}
                    - {name: 'delete', icon: 'trash', label: false}
        Role:
            class: App\Entity\EterLabel
            form:
                fields:
                    - {property: 'label_name', label: 'Etiquette'}
            list:
                fields:
                    - {property: 'label_name', label: 'Etiquette'}
                    - {property: 'eterUsers', label: 'Nombre utilisateurs'}
                actions:
                    - {name: 'edit', icon: 'pencil', label: false}
                    - {name: 'delete', icon: 'trash', label: false}
        Clan:
            class: App\Entity\EterClan
            form:
                fields:
                    - {property: 'clan_name', label: 'Nom'}
                    - {property: 'clan_members', label: 'Nombre de membres'}
                    - {property: 'clan_desc', label: 'Description'}
                    - {property: 'clan_discord', label: 'Discord'}
                    - {property: 'clan_recrut', label: 'Statut recrutement'}
                    - {property: 'clan_slogan', label: 'Devise'}
                    - {property: 'ban_pic', type: 'file', label: 'Bannière'}
#                    - {property: 'ban_pic', type: 'vich_image', label: 'Bannière de Clan', base_path: '/eter/public/img/upload/ban'}
            list:
                fields:
                    - {property: 'clan_ban', type: 'image', label: 'Bannière de Clan', base_path: '/eter/public/img/upload/ban'}
                    - {property: 'clan_name', label: 'Nom'}
                    - {property: 'clan_members', label: 'Nombre de membres'}
                    - {property: 'clan_desc', label: 'Description'}
                    - {property: 'clan_discord', label: 'Discord'}
                    - {property: 'clan_recrut', label: 'Statut recrutement'}
                    - {property: 'clan_slogan', label: 'Devise'}
                actions:
                    - {name: 'edit', icon: 'pencil', label: false}
                    - {name: 'delete', icon: 'trash', label: false}
            show:
                fields:
                    - {property: 'clan_ban', type: 'image', label: 'Bannière de Clan', base_path: '/eter/public/img/upload/ban'}
                actions:
                    - {name: 'edit', icon: 'pencil', label: false}
                    - {name: 'delete', icon: 'trash', label: false}
        Jeux:
            class: App\Entity\EterGame
            form:
                fields:
                    - {property: 'game_name', label: 'Jeux'}
                    - {property: 'game_gender', label: 'Genre(s)'}
            list:
                fields:
                    - {property: 'game_name', label: 'Jeux'}
                    - {property: 'eterUsers', label: 'Nombre utilisateurs'}
                    - {property: 'game_gender', label: 'Nombre Genres'}
                actions:
                    - {name: 'edit', icon: 'pencil', label: false}
                    - {name: 'delete', icon: 'trash', label: false}
        Genre:
            class: App\Entity\EterGender
            form:
                fields:
                    - {property: 'gender_name', label: 'Intitulé'}
            list:
                fields:
                    - {property: 'gender_name', label: 'Intitulé'}
                    - {property: 'eterGames', label: 'Nombre de Jeux'}
                actions:
                    - {name: 'edit', icon: 'pencil', label: false}
                    - {name: 'delete', icon: 'trash', label: false}
        GamePlay:
            class: App\Entity\EterGameplay
            form:
                fields:
                    - {property: 'gameplay_type', label: 'Type de gameplay'}
            list:
                fields:
                    - {property: 'gameplay_type', label: 'Type de gameplay'}
                    - {property: 'eterClans', label: 'Nombre de clans'}
                actions:
                    - {name: 'edit', icon: 'pencil', label: false}
                    - {name: 'delete', icon: 'trash', label: false}
        Info_Streamer:
            class: App\Entity\EterStreamer
            form:
                fields:
                    - {property: 'eterUser', label: 'Streamer'}
                    - {property: 'stream_url', label: 'Adresse de stream'}
                    - {property: 'stream_support', label: 'Plateforme de stream'}
            list:
                fields:
                    - {property: 'eterUser', label: 'Streamer'}
                    - {property: 'stream_url', label: 'Adresse de stream'}
                    - {property: 'stream_support', label: 'Plateforme de stream'}
                actions:
                    - {name: 'edit', icon: 'pencil', label: false}
                    - {name: 'delete', icon: 'trash', label: false}
        Evenement:
            class: App\Entity\EterEvent
            form:
                fields:
                    - {property: 'event_date', label: 'Date de déroulement'}
                    - {property: 'event_creation', label: 'Date de création'}
                    - {property: 'eventName', label: 'Nom event'}
                    - {property: 'event_winner', label: 'Vainqueur'}
                    - {property: 'event_score', label: 'Score'}
                    - {property: 'event_orga', label: 'Nombre organisateur(s)'}
                    - {property: 'eterClans', label: 'Nombre de clans participant'}
            list:
                fields:
                    - {property: 'event_date', label: 'Date'}
                    - {property: 'event_creation', label: 'Date de création'}
                    - {property: 'eventName', label: 'Nom event'}
                    - {property: 'event_winner', label: 'Vainqueur'}
                    - {property: 'event_score', label: 'Score'}
                    - {property: 'event_orga', label: 'Nombre organisateur(s)'}
                    - {property: 'eterClans', label: 'Nombre de clans participant'}
                actions:
                    - {name: 'edit', icon: 'pencil', label: false}
                    - {name: 'delete', icon: 'trash', label: false}
        Categorie:
            class: App\Entity\EterCategorie
            form:
                fields:
                    - {property: 'Cat_name', label: 'Nom de la catégorie', type: 'text'}
                    - {property: 'eterCategorie', label: 'Catégorie parent'}
            list:
                fields:
                    - {property: 'Cat_name', label: 'Nom de la catégorie'}
                    - {property: 'cat_parent', label: 'Nombre de sous-catégorie'}
                    - {property: 'eterCategorie', label: 'Catégorie parent'}
                    - {property: 'eterContents', label: 'Nombre de contenus'}
                actions:
                    - {name: 'edit', icon: 'pencil', label: false}
                    - {name: 'delete', icon: 'trash', label: false}
        Commentaires:
            class: App\Entity\EterComment
            form:
                fields:
                    - {property: 'com_content', label: 'Contenu'}
                    - {property: 'com_user', label: 'Auteur'}
                    - {property: 'content_com', label: 'Contenu commenté'}
                    - {property: 'eterComment', label: 'Commentaire parent'}
                    - {property: 'com_date', label: 'Date de création'}
            list:
                fields:
                    - {property: 'com_date', label: 'Date de création'}
                    - {property: 'com_user', label: 'Auteur'}
                    - {property: 'com_content', label: 'Contenu'}
                    - {property: 'content_com', label: 'Contenu commenté'}
                    - {property: 'eterComment', label: 'Commentaire parent'}
                    - {property: 'com_comment', label: 'Nombre de commentaire(s)'}
            actions:
                - {name: 'edit', icon: 'pencil', label: false}
                - {name: 'delete', icon: 'trash', label: false}
#                show:
#                    - {property: 'com_content', label: 'Contenu'}
#                    - {property: 'com_date', label: 'Date de création'}
#                    - {property: 'com_user', label: 'Auteur'}
#                    - {property: 'eterComment', label: 'Publication commentée'}
#                    - {property: 'com_comment', label: 'Commentaire commenté'}
        Contenus:
            class: App\Entity\EterContent
            form:
                fields:
                    - {property: 'content_user', label: 'Auteur'}
                    - {property: 'content_cat', label: 'Catégorie'}
                    - {property: 'content_name', label: 'Titre'}
                    - {property: 'content_text', label: 'Texte'}
                    - {property: 'picture', type: 'file', label: 'Image'}
                    - {property: 'content_date', label: 'Date ajout'}
                    - {property: 'content_state', label: 'Etat'}
            list:
                fields:
                    - {property: 'content_date', label: 'Date ajout'}
                    - {property: 'content_user', label: 'Auteur'}
                    - {property: 'content_pic', label: 'Image', type: 'image', base_path: '/eter/public/img/upload/artwork'}
                    - {property: 'content_name', label: 'Titre'}
                    - {property: 'content_state', label: 'Etat'}
                    - {property: 'content_cat', label: 'Catégorie'}
                    - {property: 'eterComments', label: 'Nombre de commentaire(s)'}
                actions:
                    - {name: 'edit', icon: 'pencil', label: false}
                    - {name: 'delete', icon: 'trash', label: false}
                show:
                    fields:
                        - {property: 'content_pic', type: 'image', label: 'Image', base_path: '/eter/public/img/upload/artwork'}
        Statut:
            class: App\Entity\EterState
            form:
                fields:
                    - {property: 'state_name', label: 'Intitulé'}
            list:
                fields:
                    - {property: 'state_name', label: 'Intitulé'}
                    - {property: 'eterContents', label: 'Nombre de publication(s)'}
            actions:
                - {name: 'edit', icon: 'pencil', label: false}
                - {name: 'delete', icon: 'trash', label: false}
    design:
        menu:
            - label: 'Social'
              icon: 'user-friends'
              children:
                  - {entity: 'Utilisateur', icon: 'user', label: 'Utilisateurs'}
                  - {entity: 'Role', icon: 'user-tag', label: 'Rôle'}
                  - {entity: 'Clan', icon: 'users', label: 'Clan'}
                  - {entity: 'GamePlay', icon: 'chess-knight', label: 'Gameplay'}
                  - {entity: 'Info_Streamer', icon: 'twitch', label: 'Streamer'}
            - label: 'Jeux'
              icon: 'gamepad'
              children:
                  - {entity: 'Jeux', icon: 'gamepad', label: 'Jeux'}
                  - {entity: 'Genre', icon: 'database', label: 'Genre'}
            - label: 'Evénement'
              icon:  'calendar-alt'
              children:
                  - {entity: 'Evenement', icon: 'calendar-alt', label: 'Evenement'}
            - label: 'Publication'
              icon: 'newspaper'
              children:
                  - {entity: 'Categorie', icon: 'folder-open', label: 'Catégorie'}
                  - {entity: 'Commentaires', icon: 'comments', label: 'Commentaires'}
                  - {entity: 'Contenus', icon: 'inbox', label: 'Contenus'}
                  - {entity: 'Statut', icon: 'question', label: 'Statut'}
        brand_color: '#9F1E5D'
        assets:
            css:
                - 'css/backOffice.css'
            favicon:
                path: 'img/favicon/favicon.jpg'
                mime_type: 'image/jpg'