twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/public/img/logo': images
    # Thème bootstrap pour le formulaire
    form_themes: ['form/materialize_form_layout.html.twig']
    date:
        timezone: Europe/Paris